services:
  - type: web
    name: awa-cyber-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: awa-cyber-backend
          property: port
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: SEED_ADMIN_NAME
        sync: false
      - key: SEED_ADMIN_EMAIL
        sync: false
      - key: SEED_ADMIN_PHONE
        sync: false
      - key: SEED_ADMIN_COMPANY
        sync: false
      - key: SEED_ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SETUP_KEY
        sync: false
